### ISSUE TITLE
[Question] What's the procedure for adding entries?

### ISSUE THREAD

**Issue by TFWol** [ClashSAN/sd-webui-extension-records#6]
I'm happy to see something like this exists, although I'm a little lost on a couple things:
Do we edit both the Extensions-index.md and README.md? Any prerequisites?

**Comment by ClashSAN** [comment]
>Any prerequisites?

hmm, only that all the extension functions should work with Windows.
I think that should be good, since AUTOMATIC1111 uses Windows + Nivdia and webui is primarily targeted towards these.

**Comment by TFWol** [comment]
Got it. What about the Extensions-index.md? I'm not entirely sure why it's there since A1111 already has a list. You could probably have a link to it or something so you wouldn't have to touch anything.

**Comment by ClashSAN** [comment]
deleted now, it was simply a clone the original.

**Comment by TFWol** [comment]
Ah, I see
